In [2]:
import numpy as np
import pandas as pd

In [17]:
#creating 2 arrays
a=np.arange(9).reshape(3,3)
b=(a+1)*10
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [45]:
#horizontally stack the two arrays
c=np.hstack((a,b))
c

array([[ 0,  1,  2, 10, 20, 30],
       [ 3,  4,  5, 40, 50, 60],
       [ 6,  7,  8, 70, 80, 90]])

In [46]:
#vertically stack the two arrays
d=np.vstack((a,b))
d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [18]:
#concatenating the arrays in terms of axis=1
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2, 10, 20, 30],
       [ 3,  4,  5, 40, 50, 60],
       [ 6,  7,  8, 70, 80, 90]])

In [20]:
#concatenating the arrays in  terms of axis=0
np.concatenate((a,b),axis=0)
#both the stacking and concatenating the similar to each others, except the specifying the axis

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [22]:
np.dstack((a,b)) 
#adding the depth with additional axis reffered as depth, or the third axis

array([[[ 0, 10],
        [ 1, 20],
        [ 2, 30]],

       [[ 3, 40],
        [ 4, 50],
        [ 5, 60]],

       [[ 6, 70],
        [ 7, 80],
        [ 8, 90]]])

In [24]:
#using 1-d array
one_d_a=np.arange(5)
one_d_a

array([0, 1, 2, 3, 4])

In [27]:
#another 1d array
one_d_b=(one_d_a+1)*10
one_d_b

array([110, 210, 310, 410, 510])

In [32]:
#stacking the two columns
np.column_stack((one_d_a,one_d_b))

array([[ 10, 110],
       [ 20, 210],
       [ 30, 310],
       [ 40, 410],
       [ 50, 510]])

In [35]:
#row stacking 
np.row_stack((one_d_a,one_d_b))

array([[ 10,  20,  30,  40,  50],
       [110, 210, 310, 410, 510]])

In [52]:
#spliting array into 3 columns 
y=np.hsplit(a,3)
y

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [109]:
#spliting into 2 columns
np.hsplit(c,2)

[array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]), array([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])]

In [102]:
#spliting at columns 2 and 5
h=np.hsplit(c,[2,4]) #the 2 is the first array value to be split
# and the 4 is the 4th index value to be split
h

[array([[0, 1],
        [3, 4],
        [6, 7]]), array([[ 2, 10],
        [ 5, 40],
        [ 8, 70]]), array([[20, 30],
        [50, 60],
        [80, 90]])]

In [103]:
h[0]

array([[0, 1],
       [3, 4],
       [6, 7]])

In [104]:
h[1]

array([[ 2, 10],
       [ 5, 40],
       [ 8, 70]])

In [119]:
h[2]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [121]:
# splitting along with rows
np.split(c,2, axis=1)

[array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]), array([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])]

In [122]:
d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [129]:
#spliting along with columns
np.split(d,2,axis=0)

[array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]), array([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])]

In [130]:
h=np.split(d,3,axis=0)
h

[array([[0, 1, 2],
        [3, 4, 5]]), array([[ 6,  7,  8],
        [10, 20, 30]]), array([[40, 50, 60],
        [70, 80, 90]])]

In [131]:
h[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [132]:
h[1]

array([[ 6,  7,  8],
       [10, 20, 30]])

In [133]:
h[2]

array([[40, 50, 60],
       [70, 80, 90]])

In [139]:
#vertical split in terms of rows
np.vsplit(d,2)

[array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]), array([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])]

In [140]:
np.vsplit(d,3)

[array([[0, 1, 2],
        [3, 4, 5]]), array([[ 6,  7,  8],
        [10, 20, 30]]), array([[40, 50, 60],
        [70, 80, 90]])]

In [150]:
#depth split
a=np.arange(18).reshape(3,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [153]:
h=np.dsplit(a,2) #it first conbines all the 1st column and generates all the 2nd column as an 2nd array
h

[array([[[ 0],
         [ 2],
         [ 4]],
 
        [[ 6],
         [ 8],
         [10]],
 
        [[12],
         [14],
         [16]]]), array([[[ 1],
         [ 3],
         [ 5]],
 
        [[ 7],
         [ 9],
         [11]],
 
        [[13],
         [15],
         [17]]])]

In [154]:
h[0]

array([[[ 0],
        [ 2],
        [ 4]],

       [[ 6],
        [ 8],
        [10]],

       [[12],
        [14],
        [16]]])

In [155]:
h[1]

array([[[ 1],
        [ 3],
        [ 5]],

       [[ 7],
        [ 9],
        [11]],

       [[13],
        [15],
        [17]]])

In [99]:
#useful numerical methods of numpy array
a=np.array([[9,9,3],[4,5,2],[8,8,7]])
#a=np.arange(10,19).reshape(3,3)

In [100]:
print("min and max  value of entire matrix is {0} and {1}".format(a.min(), a.max()))
print("index no of the max and min value is {0} and {1}".format(a.argmax(),a.argmin()))
print("min and max  value of entire matrix is {0} and {1}".format(a.min(), a.max()))
print("min and max  value down each column{0} and {1}".format(a.min(axis=0), a.max(axis=0)))
#reading the minimun and maximun values across each columns
print("min and max  value down each row{0} and {1}".format(a.min(axis=1), a.max(axis=1)))
#reading the minum and maximum across each rows



min and max  value of entire matrix is 2 and 9
index no of the max and min value is 0 and 5
min and max  value of entire matrix is 2 and 9
min and max  value down each column[4 5 2] and [9 9 7]
min and max  value down each row[3 2 7] and [9 5 8]


In [101]:
#calculating mean, Standard Deviation and variance
a.mean()
a.std()
a.var()

6.320987654320987

In [102]:
#calculating sum and product
a.sum()
a.prod()

4354560

In [103]:
#calculating cumulative sum and product
a.cumsum()
a.cumprod()

array([      9,      81,     243,     972,    4860,    9720,   77760,
        622080, 4354560])

In [104]:
#important
#the .all and .any methods
#applying logical operators
print((a<5).any())  #this will returns true if there is any value greater then 5 else false
print((a>5).all()) #this will returns true if all the existing values are greater then 5 else false

True
False


In [105]:
# the size attribute
#the .size method returns the total numbers in an array, matrix or 3d array
print(a.size) #size of 2-d array
print(np.arange(100,200).reshape(10,10))#2-d array
print(np.arange(100,200).reshape(5,5,4)) #3d array
print(np.arange(100,200).reshape(5,5,4).size) #size of 3d array

9
[[100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]]
[[[100 101 102 103]
  [104 105 106 107]
  [108 109 110 111]
  [112 113 114 115]
  [116 117 118 119]]

 [[120 121 122 123]
  [124 125 126 127]
  [128 129 130 131]
  [132 133 134 135]
  [136 137 138 139]]

 [[140 141 142 143]
  [144 145 146 147]
  [148 149 150 151]
  [152 153 154 155]
  [156 157 158 159]]

 [[160 161 162 163]
  [164 165 166 167]
  [168 169 170 171]
  [172 173 174 175]
  [176 177 178 179]]

 [[180 181 182 183]
  [184 185 186 187]
  [188 189 190 191]
  [192 193 194 195]
  [196 197 198 199]]]
100


In [111]:
#the ndim attribute
print(a.ndim) #shows the dimention if an array, therefore, it's 2d array, so it returned 2
b=np.array([[[[[[9]]]]]])
c=np.array([[[1,2],[2,3]],[[2,3],[3,4]]])
print(b.ndim) #returns 6 because of 6 arrays
print(c.ndim) #returns 3 because of 6 arrays

6
6
3


In [ ]:
#summary
'''In this chapter, we have examined NumPy arrays to get an understanding of their
capabilities to manipulate data and performe operations on data including selecting
elements, vectorization, Boolean selection, reshaping, stacking, concatenation,
splitting, and slicing. NumPy has many other features, but these are the ones that
are important to understand as they will set a frame of reference for understanding
the operation of pandas Series and DataFrame objects. All the concepts covered in
this chapter will be examined in much more detail in the next two chapters, where
they are applied to pandas objects, which extend these capabilities to provide a much
richer and more expressive means of representing and manipulating data than is
offered with NumPy arrays.'''